Repository statping-ng/statping-ng, pull requests merged in 2021-09, with the labels that each got.

#31 Remove snapcraft as a statping service
  snapcraft.yaml
Labels: bug, build

#33 Snap now a service and works correctly
  snapcraft.yaml
Labels: bug, build

#25 Fix for Root Dockerfile building from Dockerhub not source and also adjusting Makefile
  Dockerfile
  Makefile
  dev/docker-compose.lite.yml
  docker-compose.yml
Labels: Bug, Migration, docker, Build

#36 Add Czech language
  frontend/src/languages/czech.js
Labels: New Feature, Translation

#35 Update german language
  frontend/src/languages/german.js
Labels: Translation, Improvement

#44 Mattermost Notifier
  dev/postman.json
  notifiers/mattermost.go
  notifiers/mattermost_test.go
  notifiers/notifiers.go
Labels: New Feature, Notifier

#37 Allow chat_ids for telegram notifications
  frontend/src/forms/Notifier.vue
  notifiers/telegram.go
Labels: Improvement, Notifier

#8 Allow http webhook to set multiple headers + logging headers
  notifiers/webhook.go
  utils/utils.go
Labels: New Feature
