Repository statping-ng/statping-ng, pull requests merged in 2022-07, with the labels that each got.

#144 Typo fixed in czech.js
  frontend/src/languages/czech.js
Labels: Translation, Improvement

#138 dev: Add base.gohtml in assets [#137](https://github.com/statping-ng/…
  frontend/src/API.js
  handlers/handlers.go
  source/source.go
Labels: Improvement

#152 Build changes
  .github/workflows/1_dev.yml
  .github/workflows/2_unstable.yml
  .github/workflows/3_stable.yml
Labels: Build

#156 Fix unstable workflow file.
  .github/workflows/2_unstable.yml
Labels: Bug, Build
