Repository statping-ng/statping-ng, pull requests merged in 2023-07, with the labels that each got.

#217 Add swedish translation
  frontend/src/forms/CoreSettings.vue
  frontend/src/forms/Setup.vue
  frontend/src/languages/index.js
  frontend/src/languages/swedish.js
  source/generate_languages.go
Labels: Translation

#214 Add Notification Icon to status page for service announcements
  frontend/src/assets/scss/base.scss
  frontend/src/components/Index/Group.vue
  frontend/src/components/Index/MessagesIcon.vue
  frontend/src/icons.js
  frontend/src/pages/Index.vue
Labels: Improvement

#234 Add all possible target platforms to CI
  .github/workflows/build.yml
Labels: Migration, Build
